# Generated by Django 4.0.4 on 2022-05-18 02:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('project_id', models.CharField(max_length=30)),
                ('private_key_id', models.CharField(max_length=50)),
                ('private_key', models.CharField(max_length=1800)),
                ('client_email', models.CharField(max_length=60)),
                ('client_id', models.CharField(max_length=30)),
                ('auth_uri', models.CharField(max_length=45)),
                ('token_uri', models.CharField(max_length=50)),
                ('auth_provider_x509_cert_url', models.CharField(max_length=50)),
                ('client_x509_cert_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=-1)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auth')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.url')),
            ],
        ),
    ]
