# Generated by Django 4.0.4 on 2022-05-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='name',
            new_name='url',
        ),
    ]
