# Generated by Django 4.0.4 on 2022-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_url_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='auth',
        ),
        migrations.AddField(
            model_name='auth',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='status',
            name='file_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='status',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
